name: build sing-box

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
   - cron: "0 8 * * *"

jobs:
  cross:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          # linux
          - name: linux-amd64
            goos: linux
            goarch: amd64
            goamd64: v1
          - name: linux-amd64-v3
            goos: linux
            goarch: amd64
            goamd64: v3
          - name: linux-arm64
            goos: linux
            goarch: arm64
          - name: linux-armv5
            goos: linux
            goarch: arm
            goarm: 5
          - name: linux-armv6
            goos: linux
            goarch: arm
            goarm: 6
          - name: linux-armv7
            goos: linux
            goarch: arm
            goarm: 7
          # windows
          - name: windows-amd64
            goos: windows
            goarch: amd64
            goamd64: v1
          - name: windows-amd64-v3
            goos: windows
            goarch: amd64
            goamd64: v3
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 0
      TAGS: with_quic,with_dhcp,with_wireguard,with_clash_api,with_gvisor
    steps:
      - name: Set variables
        if: github.event_name != 'schedule'
        run: |
          echo "PRERELEASE=false" >> $GITHUB_ENV

      - name: Set variables
        if: github.event_name == 'schedule'
        run: |
          echo "PRERELEASE=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name != 'schedule'
        with:
          fetch-depth: 0
          repository: SagerNet/sing-box
          ref: main-next

      - name: Checkout
        uses: actions/checkout@v4
        if: github.event_name == 'schedule'
        with:
          fetch-depth: 0
          repository: SagerNet/sing-box
          ref: dev-next

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build
        id: build
        run: make

      - name: Test
        run: |
          echo ${{ contains(matrix.name, 'windows') }}
          echo ${{ matrix.name }}

      - name: Rename Windows
        if: ${{ contains(matrix.name, 'windows') }}
        run: mv sing-box* sing-box-${{ matrix.name }}.exe
      - name: Rename
        if: ${{ contains(matrix.name, 'linux') || contains(matrix.name, 'bsd') || contains(matrix.name, 'darwin') || contains(matrix.name, 'android') }}
        run: mv sing-box* sing-box-${{ matrix.name }}

      - name: Get sing-box version
        run: |
          chmod +x ./sing-box-linux-amd64
          version_output=$(./sing-box-linux-amd64 version)
          echo "Version Output: $version_output"
          version=$(echo "$version_output" | awk 'NR==1 {print $NF}')
          echo "Extracted Version: $version"
          echo "TAG_NAME=$version" >> $GITHUB_ENV
          echo "RELEASE_NAME=$version" >> $GITHUB_ENV

      #- name: Upload artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: sing-box-${{ matrix.name }}
      #    path: sing-box*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ env.PRERELEASE }}
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            sing-box*
